def get_user():
    return {
        "User": {
            "Userdata": {
                "login": "qwertyuiop",
                "password": "qwertyuiop",
                "sex": "M",
                "age": "13",
                "weight": "14",
                "height": "16",
            },
        "Kuritsa":"-",
        "Avokado":"-",
        "Banany":"-",
        "Bekon":"-",
        "Brokkoli":"+",
        "CHereshok sel'dereya":"-",
        "CHernosliv":"-",
        "CHesnok":"-",
        "Farsh":"-",
        "Fasol'":"-",
        "Govyadina":"+",
        "Grechka":"-",
        "Griby":"-",
        "Grusha":"-",
        "Indeyka":"-",
        "Inzhir":"-",
        "Izyum":"-",
        "Jogurt":"-",
        "Kabachok":"-",
        "Kapusta":"-",
        "Kartofel'":"-",
        "Kesh'yu":"-",
        "Klyukva":"-",
        "Kolbasa":"-",
        "Korica":"+",
        "Krabovye Palochki":"-",
        "Krahmal":"-",
        "Kukuruza":"-",
        "Kuraga":"+",
        "Lavrovyj list":"+",
        "Limon":"-",
        "Losos'":"+",
        "Luk":"-",
        "Majonez":"-",
        "Makarony":"+",
        "Manka":"-",
        "Maslo":"-",
        "Maslo olivk.":"-",
        "Maslo pods":"-",
        "Maslo pods.":"-",
        "Moloko":"-",
        "Morkov'":"+",
        "Muka":"-",
        "Ogurec":"-",
        "Ogurec marinovannyj":"-",
        "Ogurec solenyj":"-",
        "Pechen'":"+",
        "Perec":"-",
        "Perec zelenyj":"-",
        "Perlovka":"-",
        "Petrushka":"-",
        "Razryhlitel' testa":"-",
        "Ris":"-",
        "Sahar":"-",
        "Salat":"-",
        "Sel'd'":"-",
        "Shpinat":"-",
        "Smetana":"-",
        "Sol'":"-",
        "Sosiski":"-",
        "Sous soevyj":"-",
        "Sparzha":"-",
        "Specii":"-",
        "Svekla":"-",
        "Svinina":"-",
        "Syr":"-",
        "Tom.Pasta":"-",
        "Tomaty":"-",
        "Tunec":"-",
        "Tvorog":"-",
        "Ukrop":"-",
        "Uksus":"-",
        "Voda":"-",
        "Yajco":"-",
        "Zel.Goroshek":"-",
        "zelen'":"-",
        "Zelenyj luk":"-",
        "Juice": "-",
        "Tea": "-",
        "Coffee": "-",
        "Cocoa": "+",
        "Milk": "-"
        }
    }
